import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Box, Card, Button, Typography, Chip, Stack, TextField,
  InputAdornment, CircularProgress, Alert, Tab, Tabs, Dialog,
  DialogTitle, DialogContent, DialogActions, MenuItem, Select,
  FormControl, InputLabel, alpha, useTheme, IconButton, Tooltip, Stepper,
  Step, StepLabel, Divider,
} from '@mui/material';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import {
  Add, Search, FilterList, Edit, Visibility, Assignment,
  HourglassEmpty, CheckCircle, Cancel, Description,
  AutoAwesome, ContentCopy, Refresh,
} from '@mui/icons-material';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { worksheetsApi, worksheetTemplatesApi, samplesApi } from '../../api/endpoints';
import { useUIStore } from '../../store/uiStore';
import { useAuthStore } from '../../store/authStore';

const ANALYST_ROLES = ['qc_analyst', 'qa_analyst', 'analyst'];
const REVIEWER_ROLES = ['qa_manager', 'qa_reviewer', 'approver', 'reviewer', 'manager'];

type WsStatus = 'Draft' | 'In Review' | 'Approved' | 'Rejected' | 'Submitted';

interface Worksheet {
  id: string;
  wsId: string;
  title: string;
  status: WsStatus;
  assignedTo: string;
  createdDate: string;
  type?: string;
}

const STATUS_CONFIG: Record<WsStatus, { color: 'default' | 'warning' | 'success' | 'error' | 'info' }> = {
  Draft: { color: 'default' },
  'In Review': { color: 'warning' },
  Approved: { color: 'success' },
  Rejected: { color: 'error' },
  Submitted: { color: 'info' },
};

const TAB_FILTERS = [
  { label: 'All', key: 'all', filter: () => true },
  { label: 'Draft', key: 'draft', filter: (w: Worksheet) => w.status === 'Draft' },
  { label: 'In Review', key: 'review', filter: (w: Worksheet) => w.status === 'In Review' || w.status === 'Submitted' },
  { label: 'Approved', key: 'approved', filter: (w: Worksheet) => w.status === 'Approved' },
  { label: 'Rejected', key: 'rejected', filter: (w: Worksheet) => w.status === 'Rejected' },
];

// ─── Auto-Generate Dialog ──────────────────────────────────────────────────────
function AutoGenerateDialog({
  open, onClose, onSuccess, currentBranchId,
}: {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
  currentBranchId: number;
}) {
  const theme = useTheme();
  const queryClient = useQueryClient();
  const [step, setStep] = useState(0);
  const [selectedTemplate, setSelectedTemplate] = useState('');
  const [selectedSample, setSelectedSample] = useState('');
  const [title, setTitle] = useState('');
  const [priority, setPriority] = useState('Normal');
  const [notes, setNotes] = useState('');

  const { data: templatesData } = useQuery({
    queryKey: ['worksheet-templates'],
    queryFn: () => worksheetTemplatesApi.list(),
    enabled: open,
    retry: false,
  });
  const { data: samplesData } = useQuery({
    queryKey: ['samples', currentBranchId],
    queryFn: () => samplesApi.list(currentBranchId),
    enabled: open,
    retry: false,
  });

  const templates: any[] = Array.isArray(templatesData) ? templatesData : (templatesData as any)?.content ?? [];
  const samples: any[] = Array.isArray(samplesData) ? samplesData : (samplesData as any)?.content ?? [];

  const generateMutation = useMutation({
    mutationFn: () =>
      worksheetsApi.create(
        {
          title: title || `Auto-Generated from ${templates.find((t) => t.id == selectedTemplate)?.name ?? 'template'}`,
          templateId: Number(selectedTemplate),
          sampleId: selectedSample ? Number(selectedSample) : undefined,
          priority,
          notes,
          autoGenerated: true,
        },
        currentBranchId
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['worksheets', currentBranchId] });
      handleClose();
      onSuccess();
    },
  });

  const handleClose = () => {
    setStep(0);
    setSelectedTemplate('');
    setSelectedSample('');
    setTitle('');
    setPriority('Normal');
    setNotes('');
    onClose();
  };

  const selectedTpl = templates.find((t) => String(t.id) === String(selectedTemplate));

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
      <DialogTitle>
        <Stack direction="row" alignItems="center" spacing={1.5}>
          <AutoAwesome sx={{ color: theme.palette.primary.main }} />
          <Box>
            <Typography fontWeight={700}>Auto-Generate Worksheet</Typography>
            <Typography variant="caption" color="text.secondary">Create a worksheet pre-loaded with template test cases</Typography>
          </Box>
        </Stack>
      </DialogTitle>
      <DialogContent sx={{ pt: 2 }}>
        <Stepper activeStep={step} sx={{ mb: 3 }}>
          {['Select Template', 'Link Sample', 'Configure'].map((l) => (
            <Step key={l}><StepLabel>{l}</StepLabel></Step>
          ))}
        </Stepper>

        {step === 0 && (
          <Stack spacing={2}>
            <Typography variant="body2" color="text.secondary">
              Choose a worksheet template. All test cases, method references, and validation rules
              from the template will be automatically loaded into the new worksheet.
            </Typography>
            {templates.length === 0 ? (
              <Alert severity="info">No worksheet templates found. Create templates first via Admin.</Alert>
            ) : (
              <Box sx={{ display: 'grid', gap: 1.5 }}>
                {templates.map((t: any) => (
                  <Box
                    key={t.id}
                    onClick={() => setSelectedTemplate(String(t.id))}
                    sx={{
                      p: 2, borderRadius: 2, border: '2px solid',
                      borderColor: selectedTemplate === String(t.id) ? theme.palette.primary.main : theme.palette.divider,
                      cursor: 'pointer', transition: 'all 0.15s',
                      bgcolor: selectedTemplate === String(t.id) ? alpha(theme.palette.primary.main, 0.04) : 'background.paper',
                      '&:hover': { borderColor: theme.palette.primary.light },
                    }}
                  >
                    <Stack direction="row" alignItems="center" justifyContent="space-between">
                      <Box>
                        <Typography variant="body2" fontWeight={700}>{t.name ?? t.templateName ?? `Template ${t.id}`}</Typography>
                        <Typography variant="caption" color="text.secondary">{t.type ?? t.category ?? ''} · {t.testCaseCount ?? t.fields?.length ?? '?'} test cases</Typography>
                      </Box>
                      {selectedTemplate === String(t.id) && <CheckCircle color="primary" fontSize="small" />}
                    </Stack>
                  </Box>
                ))}
              </Box>
            )}
          </Stack>
        )}

        {step === 1 && (
          <Stack spacing={2}>
            <Typography variant="body2" color="text.secondary">
              Optionally link this worksheet to a sample. This associates test results with the sample's CoA workflow.
            </Typography>
            <FormControl size="small" fullWidth>
              <InputLabel>Sample (optional)</InputLabel>
              <Select value={selectedSample} label="Sample (optional)" onChange={(e) => setSelectedSample(e.target.value)}>
                <MenuItem value=""><em>None — standalone worksheet</em></MenuItem>
                {samples.filter((s: any) => s.status !== 'TESTED').map((s: any) => (
                  <MenuItem key={s.id} value={s.id} sx={{ fontSize: 13 }}>
                    {s.sampleCode ?? s.code ?? `SM-${s.id}`} — {s.sampleName ?? s.productName ?? ''}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
            {selectedTpl && (
              <Box sx={{ p: 2, borderRadius: 2, bgcolor: alpha(theme.palette.primary.main, 0.04), border: `1px solid ${theme.palette.divider}` }}>
                <Typography variant="caption" color="text.secondary" sx={{ fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.07em' }}>
                  Selected Template
                </Typography>
                <Typography variant="body2" fontWeight={700} sx={{ mt: 0.5 }}>{selectedTpl.name ?? selectedTpl.templateName}</Typography>
                <Typography variant="caption" color="text.secondary">{selectedTpl.type ?? ''}</Typography>
              </Box>
            )}
          </Stack>
        )}

        {step === 2 && (
          <Stack spacing={2.5}>
            <TextField
              label="Worksheet Title"
              fullWidth size="small"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder={`Auto-Generated from ${selectedTpl?.name ?? 'template'}`}
              helperText="Leave blank to use a default title"
            />
            <FormControl size="small" fullWidth>
              <InputLabel>Priority</InputLabel>
              <Select value={priority} label="Priority" onChange={(e) => setPriority(e.target.value)}>
                {['Low', 'Normal', 'High', 'Urgent'].map((p) => <MenuItem key={p} value={p}>{p}</MenuItem>)}
              </Select>
            </FormControl>
            <TextField label="Notes" fullWidth multiline minRows={2} size="small" value={notes} onChange={(e) => setNotes(e.target.value)} />
            <Divider />
            <Box sx={{ p: 2, borderRadius: 2, bgcolor: alpha(theme.palette.success.main, 0.04), border: `1px solid ${alpha(theme.palette.success.main, 0.2)}` }}>
              <Typography variant="body2" fontWeight={700} sx={{ mb: 1, color: theme.palette.success.dark }}>Generation Summary</Typography>
              <Typography variant="body2">Template: <strong>{selectedTpl?.name ?? '—'}</strong></Typography>
              {selectedSample && <Typography variant="body2">Sample: <strong>{samples.find((s: any) => String(s.id) === selectedSample)?.sampleCode ?? selectedSample}</strong></Typography>}
              <Typography variant="body2">Priority: <strong>{priority}</strong></Typography>
            </Box>
          </Stack>
        )}
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2.5, gap: 1 }}>
        {step > 0 && <Button variant="text" onClick={() => setStep((s) => s - 1)}>Back</Button>}
        <Box sx={{ flex: 1 }} />
        <Button variant="outlined" onClick={handleClose}>Cancel</Button>
        {step < 2 ? (
          <Button
            variant="contained"
            disabled={step === 0 && !selectedTemplate}
            onClick={() => setStep((s) => s + 1)}
          >
            Next
          </Button>
        ) : (
          <Button
            variant="contained"
            startIcon={generateMutation.isPending ? <CircularProgress size={16} /> : <AutoAwesome />}
            disabled={generateMutation.isPending}
            onClick={() => generateMutation.mutate()}
          >
            Generate Worksheet
          </Button>
        )}
      </DialogActions>
    </Dialog>
  );
}

// ─── Copy Worksheet Dialog ─────────────────────────────────────────────────────
function CopyWorksheetDialog({
  open, source, onClose, onSuccess, currentBranchId,
}: {
  open: boolean;
  source: Worksheet | null;
  onClose: () => void;
  onSuccess: () => void;
  currentBranchId: number;
}) {
  const queryClient = useQueryClient();
  const [newTitle, setNewTitle] = useState('');

  const copyMutation = useMutation({
    mutationFn: () =>
      worksheetsApi.create(
        {
          title: newTitle || `Copy of ${source?.title ?? 'worksheet'}`,
          sourceWorksheetId: Number(source?.id),
          copyFrom: Number(source?.id),
          type: source?.type,
        },
        currentBranchId
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['worksheets', currentBranchId] });
      setNewTitle('');
      onClose();
      onSuccess();
    },
  });

  return (
    <Dialog open={open} onClose={onClose} maxWidth="xs" fullWidth>
      <DialogTitle fontWeight={700}>Copy Worksheet</DialogTitle>
      <DialogContent sx={{ pt: 2 }}>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Creates a new Draft worksheet with the same template and test case structure as
          <strong> {source?.title}</strong>. Results from the original are not copied.
        </Typography>
        <TextField
          label="New Worksheet Title"
          fullWidth size="small"
          value={newTitle}
          onChange={(e) => setNewTitle(e.target.value)}
          placeholder={`Copy of ${source?.title ?? ''}`}
        />
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2.5, gap: 1 }}>
        <Button variant="outlined" onClick={onClose}>Cancel</Button>
        <Button
          variant="contained"
          startIcon={copyMutation.isPending ? <CircularProgress size={16} /> : <ContentCopy />}
          disabled={copyMutation.isPending}
          onClick={() => copyMutation.mutate()}
        >
          Copy Worksheet
        </Button>
      </DialogActions>
    </Dialog>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function WorksheetsPage() {
  const theme = useTheme();
  const [searchQuery, setSearchQuery] = useState('');
  const [activeTab, setActiveTab] = useState(0);
  const [newWsDialog, setNewWsDialog] = useState(false);
  const [autoGenDialog, setAutoGenDialog] = useState(false);
  const [copyDialog, setCopyDialog] = useState(false);
  const [copySource, setCopySource] = useState<Worksheet | null>(null);
  const [newWsForm, setNewWsForm] = useState({ title: '', type: 'Analytical', priority: 'Normal' });
  const [successMsg, setSuccessMsg] = useState('');
  const { currentBranchId } = useUIStore();
  const { user } = useAuthStore();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const isAnalyst = ANALYST_ROLES.some((role) =>
    user?.permissions?.some((p) => p.toLowerCase().includes(role))
  );
  const isReviewer = REVIEWER_ROLES.some((role) =>
    user?.permissions?.some((p) => p.toLowerCase().includes(role))
  );

  const { data: apiData, isLoading, isError, refetch } = useQuery({
    queryKey: ['worksheets', currentBranchId],
    queryFn: () => worksheetsApi.list(currentBranchId),
    retry: false,
  });

  const createMutation = useMutation({
    mutationFn: () => worksheetsApi.create({ ...newWsForm }, currentBranchId),
    onSuccess: () => {
      setNewWsDialog(false);
      setNewWsForm({ title: '', type: 'Analytical', priority: 'Normal' });
      queryClient.invalidateQueries({ queryKey: ['worksheets', currentBranchId] });
    },
  });

  const apiRows: Worksheet[] = Array.isArray(apiData)
    ? apiData.map((w: any) => ({
        id: String(w.id ?? w.worksheetId),
        wsId: w.worksheetCode ?? w.code ?? `WS-${w.id}`,
        title: w.title ?? w.name ?? 'Untitled',
        status: w.status ?? 'Draft',
        assignedTo: w.assignedTo?.username ?? w.assignedToName ?? 'Unassigned',
        createdDate: w.createdAt?.split('T')[0] ?? w.createdDate ?? '',
        type: w.type ?? '',
      }))
    : [];

  const statusCounts = {
    all: apiRows.length,
    draft: apiRows.filter((w) => w.status === 'Draft').length,
    review: apiRows.filter((w) => w.status === 'In Review' || w.status === 'Submitted').length,
    approved: apiRows.filter((w) => w.status === 'Approved').length,
    rejected: apiRows.filter((w) => w.status === 'Rejected').length,
  };

  const filteredRows = apiRows
    .filter(TAB_FILTERS[activeTab].filter)
    .filter((item) =>
      item.wsId.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.assignedTo.toLowerCase().includes(searchQuery.toLowerCase())
    );

  const columns: GridColDef[] = [
    {
      field: 'wsId', headerName: 'ID', width: 140,
      renderCell: (p) => (
        <Typography variant="body2" sx={{ fontFamily: 'monospace', fontWeight: 600, color: theme.palette.primary.main }}>
          {p.value}
        </Typography>
      ),
    },
    { field: 'title', headerName: 'Title', flex: 2, minWidth: 240 },
    {
      field: 'status', headerName: 'Status', width: 130,
      renderCell: (p) => {
        const cfg = STATUS_CONFIG[p.value as WsStatus] ?? { color: 'default' as const };
        return <Chip label={p.value} color={cfg.color} size="small" />;
      },
    },
    { field: 'assignedTo', headerName: 'Assigned To', flex: 1, minWidth: 150 },
    { field: 'createdDate', headerName: 'Created Date', width: 130 },
    {
      field: 'actions', headerName: 'Actions', width: 240, sortable: false,
      renderCell: (p) => (
        <Stack direction="row" spacing={0.5} alignItems="center">
          {isAnalyst && (
            <Button
              variant="text" size="small" color="primary"
              startIcon={<Edit fontSize="small" />}
              onClick={() => navigate(`/worksheets/${p.row.id}/execute`)}
              sx={{ fontSize: 12, px: 1 }}
            >
              Analyze
            </Button>
          )}
          {isReviewer && (
            <Button
              variant="text" size="small" color="secondary"
              startIcon={<Visibility fontSize="small" />}
              onClick={() => navigate(`/worksheets/${p.row.id}/review`)}
              sx={{ fontSize: 12, px: 1 }}
            >
              Review
            </Button>
          )}
          {!isAnalyst && !isReviewer && (
            <Button
              variant="text" size="small" color="primary"
              onClick={() => navigate(`/worksheets/${p.row.id}/review`)}
              sx={{ fontSize: 12, px: 1 }}
            >
              View
            </Button>
          )}
          <Tooltip title="Copy worksheet structure">
            <IconButton
              size="small"
              onClick={() => { setCopySource(p.row); setCopyDialog(true); }}
              sx={{ color: 'text.secondary' }}
            >
              <ContentCopy sx={{ fontSize: 16 }} />
            </IconButton>
          </Tooltip>
        </Stack>
      ),
    },
  ];

  return (
    <Box sx={{ p: 3 }}>
      <Stack direction={{ xs: 'column', sm: 'row' }} alignItems={{ sm: 'center' }} justifyContent="space-between" spacing={2} sx={{ mb: 3 }}>
        <Box>
          <Typography variant="h4" fontWeight={700}>Worksheets</Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
            Worksheet lifecycle, execution data, and review history.
          </Typography>
        </Box>
        <Stack direction="row" spacing={1}>
          <IconButton size="small" onClick={() => refetch()}><Refresh fontSize="small" /></IconButton>
          <Tooltip title="Auto-generate a worksheet from a template">
            <Button
              variant="outlined"
              startIcon={<AutoAwesome />}
              onClick={() => setAutoGenDialog(true)}
            >
              Auto-Generate
            </Button>
          </Tooltip>
          <Button variant="contained" startIcon={<Add />} onClick={() => setNewWsDialog(true)}>
            New Worksheet
          </Button>
        </Stack>
      </Stack>

      {successMsg && (
        <Alert severity="success" sx={{ mb: 2 }} onClose={() => setSuccessMsg('')}>
          {successMsg}
        </Alert>
      )}

      {/* Stat cards */}
      <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 2, mb: 3 }}>
        {[
          { label: 'Total', count: statusCounts.all, icon: <Description />, color: theme.palette.primary.main },
          { label: 'Draft', count: statusCounts.draft, icon: <Assignment />, color: theme.palette.grey[600] },
          { label: 'In Review', count: statusCounts.review, icon: <HourglassEmpty />, color: theme.palette.warning.main },
          { label: 'Approved', count: statusCounts.approved, icon: <CheckCircle />, color: theme.palette.success.main },
          { label: 'Rejected', count: statusCounts.rejected, icon: <Cancel />, color: theme.palette.error.main },
        ].map((stat) => (
          <Card key={stat.label} sx={{ p: 2 }}>
            <Stack direction="row" alignItems="center" spacing={1.5}>
              <Box sx={{
                width: 38, height: 38, borderRadius: 2,
                bgcolor: alpha(stat.color, 0.1),
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                color: stat.color,
              }}>
                {stat.icon}
              </Box>
              <Box>
                <Typography variant="h5" fontWeight={700}>{stat.count}</Typography>
                <Typography variant="caption" color="text.secondary">{stat.label}</Typography>
              </Box>
            </Stack>
          </Card>
        ))}
      </Box>

      {/* Table card */}
      <Card>
        <Box sx={{ borderBottom: 1, borderColor: 'divider', px: 2 }}>
          <Tabs value={activeTab} onChange={(_, v) => setActiveTab(v)} sx={{ minHeight: 44 }}>
            {TAB_FILTERS.map((t) => (
              <Tab
                key={t.key}
                label={`${t.label} (${statusCounts[t.key as keyof typeof statusCounts]})`}
                sx={{ minHeight: 44, py: 0, fontSize: 13 }}
              />
            ))}
          </Tabs>
        </Box>

        <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ p: 2, borderBottom: `1px solid ${theme.palette.divider}` }}>
          <TextField
            placeholder="Search by ID, title, or analyst…"
            size="small"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start"><Search sx={{ fontSize: 18 }} /></InputAdornment>
              ),
            }}
            sx={{ flex: 1 }}
          />
          <Button variant="outlined" size="small" startIcon={<FilterList />}>Filter</Button>
        </Stack>

        {isError && (
          <Alert severity="warning" sx={{ mx: 2, mt: 2 }}>
            Could not load worksheets from the server. Please try again.
          </Alert>
        )}

        <Box sx={{ height: 520 }}>
          {isLoading ? (
            <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
              <CircularProgress />
            </Box>
          ) : (
            <DataGrid
              rows={filteredRows}
              columns={columns}
              pageSizeOptions={[10, 25, 50]}
              initialState={{ pagination: { paginationModel: { pageSize: 10 } } }}
              disableRowSelectionOnClick
              sx={{
                border: 'none',
                '& .MuiDataGrid-cell': { borderColor: theme.palette.divider },
                '& .MuiDataGrid-columnHeaders': { bgcolor: theme.palette.grey[50] },
              }}
            />
          )}
        </Box>
      </Card>

      {/* Manual Create Dialog */}
      <Dialog open={newWsDialog} onClose={() => setNewWsDialog(false)} maxWidth="sm" fullWidth>
        <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
          <Assignment color="primary" />
          Create New Worksheet
        </DialogTitle>
        <DialogContent sx={{ pt: 2 }}>
          <Stack spacing={2.5}>
            <TextField
              label="Worksheet Title" fullWidth required size="small"
              value={newWsForm.title}
              onChange={(e) => setNewWsForm((p) => ({ ...p, title: e.target.value }))}
              placeholder="e.g., HPLC Assay - Batch 2024-045"
            />
            <FormControl size="small" fullWidth>
              <InputLabel>Type</InputLabel>
              <Select value={newWsForm.type} label="Type" onChange={(e) => setNewWsForm((p) => ({ ...p, type: e.target.value }))}>
                {['Analytical', 'Stability', 'Dissolution', 'Microbial', 'Physical', 'Other'].map((t) => (
                  <MenuItem key={t} value={t}>{t}</MenuItem>
                ))}
              </Select>
            </FormControl>
            <FormControl size="small" fullWidth>
              <InputLabel>Priority</InputLabel>
              <Select value={newWsForm.priority} label="Priority" onChange={(e) => setNewWsForm((p) => ({ ...p, priority: e.target.value }))}>
                {['Low', 'Normal', 'High', 'Urgent'].map((p) => (
                  <MenuItem key={p} value={p}>{p}</MenuItem>
                ))}
              </Select>
            </FormControl>
          </Stack>
        </DialogContent>
        <DialogActions sx={{ px: 3, pb: 2.5, gap: 1 }}>
          <Button onClick={() => setNewWsDialog(false)} variant="outlined">Cancel</Button>
          <Button
            variant="contained"
            disabled={!newWsForm.title.trim() || createMutation.isPending}
            startIcon={createMutation.isPending ? <CircularProgress size={16} /> : <Add />}
            onClick={() => createMutation.mutate()}
          >
            Create Worksheet
          </Button>
        </DialogActions>
      </Dialog>

      {/* Auto-Generate Dialog */}
      <AutoGenerateDialog
        open={autoGenDialog}
        onClose={() => setAutoGenDialog(false)}
        onSuccess={() => setSuccessMsg('Worksheet generated successfully from template.')}
        currentBranchId={currentBranchId}
      />

      {/* Copy Dialog */}
      <CopyWorksheetDialog
        open={copyDialog}
        source={copySource}
        onClose={() => setCopyDialog(false)}
        onSuccess={() => setSuccessMsg('Worksheet copied successfully.')}
        currentBranchId={currentBranchId}
      />
    </Box>
  );
}
